- name: Data Stewards
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/overview/overview-benefit.md
    - reproducible-research/overview/overview-barriers.md
    - reproducible-research/overview/overview-resources.md
    - reproducible-research/rdm.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/overview.md
    - reproducible-research/open.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-source.md
    - reproducible-research/open/open-hardware.md
    - reproducible-research/open/open-access.md
    - reproducible-research/open/open-notebooks.md
    - reproducible-research/open/open-scholarship.md
    - reproducible-research/vcs.md
    - reproducible-research/vcs/vcs-workflow.md
    - reproducible-research/vcs/vcs-data.md
    - reproducible-research/licensing.md
    - reproducible-research/licensing/licensing-compatibility.md
    - reproducible-research/licensing/licensing-ethical-source.md
    - reproducible-research/licensing/licensing-data.md
    - reproducible-research/rdm.md
    - reproducible-research/rdm/rdm-data.md
    - reproducible-research/rdm/rdm-find.md
    - reproducible-research/rdm/rdm-dmp.md
    - reproducible-research/rdm/rdm-fair.md
    - reproducible-research/rdm/rdm-personal.md
    - reproducible-research/rdm/rdm-storage.md
    - reproducible-research/rdm/rdm-spreadsheets.md
    - reproducible-research/rdm/rdm-metadata.md
    - reproducible-research/rdm/rdm-methods.md
    - reproducible-research/rdm/rdm-elns.md
    - reproducible-research/rdm/rdm-data-curation.md
    - reproducible-research/rdm/rdm-visualisation.md
    - reproducible-research/rdm/rdm-repository.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/rdm/rdm-article.md
    - reproducible-research/rdm/rdm-checklist.md
    - reproducible-research/rdm/rdm-stories.md
    - reproducible-research/rdm/rdm-resources.md
    - reproducible-research/renv.md
    - reproducible-research/compendia.md
    - project-design/project-design.md
    - project-design/pd-overview.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/info-management/filenaming.md
    - project-design/data-security/sdp.md
    - project-design/data-security/sdpm.md
    - project-design/data-security/sdpw.md
    - project-design/data-security/data-governance.md
    - project-design/missing-data.md
    - project-design/risks-of-bias.md
    - communication/communication.md
    - communication/comms-overview.md
    - communication/comms-overview/comms-overview-principles.md
    - communication/comms-overview/comms-overview-accessibly.md
    - communication/open.md
    - communication/blogs.md
    - communication/presentations.md
    - communication/research-objects.md
    - communication/citable.md
    - communication/dif-articles.md
    - collaboration/collaboration.md
    - collaboration/stakeholder-engagement.md
    - collaboration/leadership.md
    - collaboration/research-infrastructure-roles.md
    - collaboration/research-infrastructure-roles/data-steward.md
    - collaboration/research-infrastructure-roles/data-steward-personal-story.md
    - ethical-research/ethical-research.md
    - ethical-research/ethics-intro.md
    - ethical-research/ethics-committees.md
    - ethical-research/cultural-change.md
    - ethical-research/data-hazards.md
    - community-handbook/accessibility.md
  colour: deeppink
  description: >
    Data Steward is an umbrella term for numerous support roles that involve the creation, management and usage of research data. These can be very hands-on roles involving daily data analysis or roles that are more policy and advising-focused. Data Stewards are an important part of scientific communities, supporting recommended data management practices and saving researchers time by supporting them in these efforts. Data Stewards tend to have scientific backgrounds and can have the technical skills needed to analyse and manage both data and software (see also the resources curated for Research Software Engineers). This curated set of chapters will point. Data Stewards to topics and practices important for working with data and communicating with researchers.
- name: Research Community Management - Concepts
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/open.md
    - reproducible-research/licensing.md
    - reproducible-research/rdm.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/code-documentation.md
    - reproducible-research/reviewing.md
    - reproducible-research/compendia.md
    - project-design/project-design.md
    - project-design/pd-overview.md
    - communication/communication.md
    - communication/comms-overview.md
    - communication/comms-overview/comms-overview-principles.md
    - communication/comms-overview/comms-overview-accessibly.md
    - collaboration/collaboration.md
    - collaboration/research-infrastructure-roles/community-manager.md
    - collaboration/stakeholder-engagement.md
    - ethical-research/ethical-research.md
    - ethical-research/ethics-intro.md
    - ethical-research/cultural-change.md
    - community-handbook/community-handbook.md
    - community-handbook/accessibility.md
    - community-handbook/acknowledgement.md
  colour: orange
  description: >
   Research Community Managers work to engage and organise groups of scientists, researchers and/or patients and the public around shared research topics and objectives. This curated set of chapters will allow them to gain awareness and knowledge of relevant best practices in open data science and concepts important to community building.
- name: Research Community Management - Operations
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/open.md
    - reproducible-research/open/open-checklist.md
    - project-design/project-design.md
    - project-design/pd-design-overview/pd-checklist.md
    - collaboration/collaboration.md
    - collaboration/new-community/new-community-guide.md
    - collaboration/team-manual/team-manual-on-off-boarding.md
    - collaboration/event-tools.md
    - collaboration/organising-meetings.md
    - collaboration/chairing.md
    - collaboration/coworking.md
    - collaboration/ppie-events.md
    - collaboration/remote-collab.md
    - collaboration/hybrid-collab.md
    - community-handbook/community-handbook.md
    - community-handbook/communication-channels.md
    - community-handbook/newsletters.md
    - community-handbook/community-calls.md
    - community-handbook/fireside-chat.md
    - community-handbook/presenting.md
    - community-handbook/templates.md
  colour: red
  description: >
    Community management often requires designing processes within the community to streamline aspects of collaboration, communication, and public engagement. This curated set of chapters will allow community managers and community management enthusiasts to dive into the operational aspects of building, sustaining and expanding their communities.
- name: Early Career Researchers
  files:
    - project-design/project-design.md
    - project-design/pd-design-overview/pd-checklist.md
    - collaboration/github-novice.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/pd-overview.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/overview/overview-benefit.md
    - reproducible-research/overview/overview-barriers.md
    - reproducible-research/overview/overview-resources.md
    - reproducible-research/rdm.md
    - reproducible-research/vcs.md
    - project-design/pd-overview.md
    - project-design/pd-overview/pd-overview-methods.md
    - project-design/data-security/sdp.md
    - communication/communication.md
    - communication/comms-overview.md
    - communication/comms-overview/comms-overview-principles.md
    - communication/dif-articles.md
    - communication/presentations.md
    - communication/social-media.md
    - collaboration/collaboration.md
    - collaboration/github-novice/github-novice-advanced.md
    - ethical-research/ethics-intro.md
  colour: blue
  description: >
    Early Career Researchers (ECRs) are students, PhDs and early-stage postdocs
    who may not have a lot of experience in contributing to research projects
    from start to finish. This curated set of chapters will allow them to
    understand what best practices apply at different stages of development to
    ensure research reproducibility.
- name: Project Leaders
  files:
    - collaboration/collaboration.md
    - collaboration/leadership.md
    - project-design/project-design.md
    - project-design/pd-overview/pd-overview-planning.md
    - project-design/pd-overview/pd-overview-repro.md
    - project-design/pd-overview/pd-overview-methods.md
    - project-design/pd-overview/pd-overview-version.md
    - project-design/pd-design-overview/pd-checklist.md
    - project-design/pd-design-overview/project-repo.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/overview/overview-barriers.md
    - reproducible-research/open.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-source.md
    - communication/communication.md
    - communication/aa.md
    - communication/aa/aa-tips.md
  colour: purple
  description: >
    Project leaders are people who are responsible for project planning,
    resource allocation and other decision-making for and with the involvement
    of their project team. This curated set of chapters will point them to
    relevant tools and practices that they can use for managing their projects
    while ensuring transparency, reproducibility, collaboration and ethical
    practices throughout the lifecycle of research.
- name: Research Software Engineers
  files:
    - communication/citable.md
    - communication/citable/citable-otherscite.md
    - communication/citable/citable-cite.md
    - collaboration/collaboration.md
    - collaboration/research-infrastructure-roles.md
    - collaboration/research-infrastructure-roles/rse.md
    - collaboration/research-infrastructure-roles/rse-personal-story.md
    - collaboration/maintain-review.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/pd-design-overview/project-repo/project-repo-advanced.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/open.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-source.md
    - reproducible-research/vcs.md
    - reproducible-research/licensing.md
    - reproducible-research/code-quality.md
    - reproducible-research/testing.md
    - reproducible-research/reviewing.md
    - reproducible-research/renv.md
    - reproducible-research/binderhub.md
    - reproducible-research/ci.md
  colour: white
  description: >
    Research Software Engineers are programmers working in an academic context
    who play crucial roles in projects involving data and technology. This
    curated set of chapters will point them to open source and reproducibility
    practices important for working with data and developing software tools.
- name: Software Citation
  files:
    - communication/citable.md
    - communication/citable/citable-steps.md
    - communication/citable/citable-cite.md
    - communication/citable/citable-cff.md
    - communication/citable/citable-cffinit.md
    - communication/citable/citable-linking.md
    - communication/citable/citable-orcid.md
    - communication/citable/citable-resources.md
    - communication/citable/citable-otherscite.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/open.md
    - reproducible-research/open/open-source.md
    - reproducible-research/licensing.md
    - reproducible-research/rdm/rdm-metadata.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/code-reuse.md
    - reproducible-research/code-reuse/code-reuse-overview.md
  colour: skyblue
  description: >
    From research to government, every sector strongly relies upon the use of
    research software. This curated set of chapters guides the sharing and
    citation of software components from source code to computational workflows
    and executables while attributing all contributors fairly.
- name: Data Science Without Borders
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/vcs.md
    - reproducible-research/vcs/vcs-checklist.md
    - reproducible-research/open.md
    - reproducible-research/open/open-source.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-hardware.md
    - reproducible-research/open/open-access.md
    - reproducible-research/open/open-scholarship.md
    - reproducible-research/licensing.md
    - reproducible-research/rdm.md
    - reproducible-research/rdm/rdm-dmp.md
    - reproducible-research/rdm/rdm-fair.md
    - reproducible-research/rdm/rdm-metadata.md
    - reproducible-research/rdm/rdm-spreadsheets.md
    - reproducible-research/rdm/rdm-data-curation.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/rdm/rdm-checklist.md
    - reproducible-research/code-documentation.md
    - reproducible-research/testing.md
    - reproducible-research/testing/testing-overview.md
    - reproducible-research/testing/testing-checklist.md
    - reproducible-research/code-quality.md
    - reproducible-research/code-quality/code-quality-style.md
    - reproducible-research/reviewing/reviewing-workflow.md
    - reproducible-research/reviewing/reviewing-checklist.md
    - reproducible-research/code-reuse/code-reuse-details.md
    - project-design/project-design.md
    - project-design/pd-design-overview/pd-checklist.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/info-management/filenaming.md
    - project-design/data-security/sdp.md
    - project-design/data-security/sdp/metadata.md
    - project-design/data-security/sdpm.md
    - project-design/data-security/sdpw.md
    - project-design/data-security/data-governance.md
    - project-design/missing-data.md
    - project-design/risks-of-bias.md
    - communication/communication.md
    - communication/os-comms.md
    - communication/dif-articles.md
    - communication/presentations.md
    - communication/research-objects.md
    - communication/citable/citable-steps.md
    - communication/aa.md
    - community-handbook/translation/translation-localisation.md
    - collaboration/remote-collab.md
    - collaboration/github-novice.md
    - collaboration/maintain-review.md
    - collaboration/organising-meetings.md
    - collaboration/coworking.md
    - collaboration/organising-conference.md
    - collaboration/chairing.md
    - collaboration/event-tools.md
    - collaboration/collaboration.md
    - collaboration/shared-ownership.md
    - collaboration/team-manual.md
    - collaboration/stakeholder-engagement.md
    - ethical-research/ethics-intro.md
    - ethical-research/law-policy.md
    - ethical-research/ethics-open-source-governance.md
    - ethical-research/cultural-change.md
  colour: green
  description: >
    For effective collaboration among international groups,
    such as in the Data Science Without Borders project,
    it is essential to learn, adopt, and implement best practices
    in open, reproducible, ethical, and inclusive data science.
    These curated chapters will provide starting points, helping
    you navigate a broader set of practices in The Turing Way.
