- name: DSG
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - collaboration/collaboration
    - collaboration/github-novice
    - collaboration/github-novice/github-novice-advanced
    - collaboration/leadership
  colour: white
- name: Enrichment Students
  files:
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - reproducible-research/reproducible-research
    - reproducible-research/overview
  colour: blue
- name: Group Leaders
  files:
    - project-design/project-design
    - project-design/pd-overview
    - project-design/pd-overview/pd-overview-planning
    - project-design/pd-overview/pd-overview-repro
    - project-design/pd-overview/pd-overview-methods
    - project-design/pd-overview/pd-overview-version
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-definitions
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: purple
- name: Life Scientists
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: green
