name: "\u2728 General"
description: Have a different idea?
body:
  - type: markdown
    attributes:
      value: |
        Please complete the following sections when you open an issue.
  - type: textarea
    attributes:
      label: Summary
      description: |
        Please provide a detailed description of the change or addition you are proposing, or the question you're asking.
        Please provide as much context as possible and link to related issues and/or pull requests.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs to be done?
      description:
        We suggest using bullets (indicated by * or -) and filled checkboxes [x] here.
      placeholder: |
        - [ ] …
        - [ ] …
  - type: textarea
    attributes:
      label: Who can help?
      description: |
        Suggest people who can help.
      placeholder: |
        - …
        - …
