name: "Book Dash Checklist"
description: Book Dash planning checklist
title: "Book Dash checklist <DATE>"
labels: book_dash
body:
- type: markdown
  attributes:
    value: |
      This issue is for the event organisers, **if you are an applicant please use this form to submit your application: (NEED LINK).** This application will likely take 30 minutes to complete. You can use this template document with all the questions to prepare your draft: [https://tinyurl.com/tw-bookdash-template](https://tinyurl.com/tw-bookdash-template)
      **If you would like to host a local hub please use this google form to register you interest** (NEED LINK)
- type: input
  id: date
  attributes:
    label: Date
    description: |
      What is the date of the book dash?
  validations:
    required: true
- type: checkboxes
  id: before
  attributes:
    label:  Schedule the Book Dash and prepare the application
    description:
    options:
      - label: Finalise dates based on the location and core team’s availability
      - label: Update the application form (NEED LINK)
      - label: Update the [application template](https://tinyurl.com/tw-bookdash-template)
      - label: "**Be sure to include the following information**"
      - label: What financial support will be available for either online or in-person events?
      - label: What arrangements will be available online (such as online helpers and designated mentors) or on-site (such as quiet room and child care) for in-person events?
      - label: Accessibility information such as live captioning for in-person events and quiet room/child nursing room for in-person events
      - label: The maximum limit for financial support requests for online (such as for headphones) and in-person (such as for travel and accommodation) events
- type: checkboxes
  id: announcement
  attributes:
    label:  Two to three months ahead - announce the Book Dash and invite applications
    description:
    options:
      - label: Write a short description for promoting the event, including a link to the application
      - label: Announce the Book Dash in the newsletter and promote on Twitter
      - label: Invite returing participants to join the Book Dash planning committee
      - label: Close the application round in time (minimum 1 month ahead of the event)
      - label: Set up a form for reviewing applications (see rubrics for scoring applications for details) (NEED LINK)
- type: checkboxes
  id: logistics
  attributes:
    label:  Update documents and set up online platform
    description:
    options:
      - label: Set up an online platform (Zoom or other accessible software) for remote collaboration
      - label: Create a HackMD index page for the event - [template](https://hackmd.io/@turingway/bookdash-nov2022-index)
      - label: Update shared HackMD for pre-event calls, book dash event and feedback (NEED LINKS)
      - label: Copy the Book Dash attendees Eventbrite page from last round and set a registration code
      - label: Copy the share out Eventbrite page (2 sessions)
      - label: Send a reminder in next newsletter
- type: checkboxes
  id: planning
  attributes:
    label:  Initial planning committee meeting (TIMELINE?)
    description:
    options:
      - label: Check that all documents and forms have been updated with correct dates and links (email drafts, templates, Eventbrite)
      - label: Schedule onboarding calls 1 week before the event, find volunteers to host
      - label: Schedule GitHub intro session 1 week before the event, find volunteer(s) to host
      - label: Find volunteers to run social events during the Book Dash (discussion sessions, meals, informal chats)
      - label: Find volunteers to run community share out sessions on the last day
      - label: Check if there is anything else organisers would like to suggest or get involved in
      - label: Think about who else needs to be invited, like artists, speakers, more diverse participants
- type: checkboxes
  id: planning2
  attributes:
    label:  Application review meeting (TIMELINE?)
    description:
    options:
      - label: Review applications using Book Dash Rubrics for selection (NEED LINK)
      - label: Identify helpers and mentors from the applicants and core members and invite them
      - label: Allocate tasks for during and after the event
- type: textarea
  id: tasks
  attributes:
    label: Tasks
    description: "Record your assigned tasks here"
- type: checkboxes
  id: invites
  attributes:
    label: Invite participants (TIMELINE?)
    description:
    options:
      - label: Send an email to the selected attendees with Eventbrite page and registration code
      - label: Send an email to the unselected attendees with feedback
      - label: Set up an email chain and a Slack channel to connect all members and share updates
      - label: Provide details on Code of Conduct, contribution guideline and ways to get involved in an ongoing discussion
      - label: Update presentation for introducing the project to the participants on day one of the Book Dash
- type: checkboxes
  id: online
  attributes:
    label: Additional tasks for an online event
    description:
    options:
      - label: Set up a Slack channel and invite all attendees
      - label: Share all notes, agenda and info by email, and pin on the Slack channel
      - label: Ask them to choose at least one contribution session (2.5 hours) for each day of the Book Dash to ensure flexibility (rather than blocking the full day) -- this is for everyone joining online (see in person participation requirement below)
      - label: Collect addresses if something needs to be posted
      - label: "**Communicate the following prerequisites to online attendees**"
      - label: An active GitHub account
      - label: Participation in at least one pre-event onboarding call or a Collaboration Cafe
      - label: Some experience with using GitHub or attendance at the Book Dash GitHub session
      - label: Familiarity with The Turing Way contribution guidelines and Code of Conduct
      - label: Willingness to collaborate with others
- type: checkboxes
  id: in_person
  attributes:
    label:  Additional tasks for an in-person event
    description:
    options:
      - label: Book location for in-person events
      - label: Collate participants’ preference for travel, meal, accommodation, and accessibility request through the registration form
      - label: Send an email to the participants regarding their travel, accommodation, schedule, and meal
      - label: Book catering for lunch and coffee breaks
      - label: Double-check with each participant if their plan as given on their registration hasn’t changed
- type: checkboxes
  id: travel
  attributes:
    label:  Funding for travel and accommodation, if applicable
    description:
    options:
      - label: Book hotels rooms for people who requested accommodation
      - label: Book travel for those who requested - or provide reimbursement option
      - label: Double-check the details for travel and accommodation with each participant
      - label: Book meals/catering for people
      - label: Mention what meals will be offered as default - and ask participants to get in touch if another meal type is required
- type: checkboxes
  id: 2weeks_before
  attributes:
    label: Two weeks before (IS THIS CORRECT? OR SOONER?)
    description:
    options:
      - label: Create a GitHub issue to collect bios and highlights in order to add participants to the Contributors Record
      - label: "**Send a reminder email to register on Eventbrite. Include the following formation**"
      - label: Available grants for financial support
      - label: GitHub intro session details
      - label: Onboarding call details
      - label: Reimbursement process
- type: checkboxes
  id: week_before
  attributes:
    label: One week before
    description:
    options:
      - label: Hold intro to GitHub session
      - label: Hold onboarding calls to share logistics and facilitate the drafting of SMART goals
      - label: Group participants into the proposed working groups as per their SMART goals from the onboarding call
- type: checkboxes
  id: onboarding
  attributes:
    label: Day one - onboarding
    description:
    options:
      - label: Welcome everyone (for each slot)
      - label: Ask to fill the icebreaker
      - label: One of the organisers delivers introduction talk
      - label: Create breakout groups for people working on
- type: checkboxes
  id: sessions
  attributes:
    label: During the event - host coworking sessions with Pomodoro sessions 30-35 mins long
    description:
    options:
      - label: At the beginning of the session, ask people to document or verbally share their plan for the session
      - label: End each session with any report people want to make
      - label: Give a 5 minute break before entering the next Pomodoro
      - label: Keep last 10 minutes for final reporting and co-documenting the work that took place during the Pomodoro
      - label: If an artist, illustrator or consultant is invited, coordinate the schedule with participants so they have the chance to engage
      - label: Run a social session each day. These are run by organisers to ensure everyone has the chance to connect informally
- type: checkboxes
  id: last_day
  attributes:
    label: Final day - host a community share out the event on the last day to demonstrate and celebrate the contributions made by everyone during the Book Dash
    description:
    options:
      - label: Ask for feedback (plus and delta)
      - label: Share the GitHub issue for adding bios and highlight
      - label: Take screenshots or group photos (with permission) to share in reports or social media
- type: checkboxes
  id: after
  attributes:
    label: After the Book Dash
    options:
      - label: Send a thank you email to everyone for their work
      - label: Move bios and highlights from the GitHub issue to the Contributors Record
      - label: Summarise the event (number of pull requests, issue, chapters, and other significant news) to share with the participants
      - label: Share the update via the newsletter
      - label: Develop a report with highlights and updates on GitHub
      - label: Set up a debrief meeting with the planning committee
      - label: Send a thank you note (or a package when possible) to the planning committee
