name: "\U0001F4D1 Request Translation"
description: Propose a translation
title: "[TRANSLATION]:"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose a tnraslation.
  - type: textarea
    attributes:
      label: Summary
      description: |
        Please provide a detailed description of the language/languages that you want to translate to and the chapters that you would like to translate.
        Please provide as much context as possible and link to related issues and/or pull requests.
        Providing links to sections you're referencing for clarity is highly encouraged.
    validations:
      required: true
  - type: input
    attributes:
      label: Target language
      description: What is/are the target language/languages?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Translation options
      options:
        - label: I wish to be manager in Crowdin for entries in this language.
        - label: I will only proofread translation for this language.
        - label: I have a local translation to be uploaded to the Translation Memory?
  - type: textarea
    attributes:
      label: Chapters to translation
      description: Which chapters do you want to translate?
      placeholder: |
        - …
        - …
  - type: textarea
    id: who_can_help
    attributes:
      label: Who can help?
      description: Suggest people who can help.
      placeholder: |
        - …
        - …
