name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This might depend on how the github token is set up in the project as an environment variable
